name: retailer_data_project
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  retailer_data_project:
    base:
      +materialized: view
      +schema: "{{ target.name == 'prod' and 'base' or 'base' }}"
    intermediate:
      +materialized: view
      +schema: "{{ target.name == 'prod' and 'intermediate' or 'intermediate' }}"
    analytics:
      +materialized: table
      +schema: "{{ target.name == 'prod' and 'analytics' or 'analytics' }}"