select
    _file,
    _line,
    _modified as _modified_ts,
    _fivetran_synced as _fivetran_synced_ts,
    current_timestamp as _base_updated_ts,
    row_id as _source_row_id,
    customer_id,
    customer_name,
    segment,
    city,
    state,
    postal_code,
    country,
    market,
    region,
    product_id,
    product_name,
    category,
    sub_category,
    order_id,
    order_date,
    order_priority,
    ship_date,
    ship_mode,
    quantity,
    sales,
    discount,
    profit
from {{ source("google_drive", "transactions") }}
